import { OrphanData } from '@/managers/data/WorkspaceDataManager';
import { selectEndpoints, selectServices } from '@/state/active/selectors';
import { Alert, Button, Sheet, Stack, Typography } from '@mui/joy';
import { useSelector } from 'react-redux';
import { OrphanResolution, OrphanResolutionDropdown } from './OrphanResolutionDropdown';
import { Fragment, useMemo, useState } from 'react';
import { Check, Warning } from '@mui/icons-material';
import { OrphanResolutionSummary } from './OrphanResolutionSummary';
import { useAppDispatch } from '@/state/store';
import { activeActions } from '@/state/active/slice';
import { uiActions } from '@/state/ui/slice';
import { groupBy } from '@/utils/variables';
import { Endpoint, Service } from '@/types/data/workspace';
import { itemActions } from '@/state/items';

interface AdoptionOverlayProps {
	orphanData: OrphanData | null;
}

type OrphanStrategy = Record<string, string | OrphanResolution>;

const resVals: string[] = Object.values(OrphanResolution);

function getGroup(strat?: string) {
	if (strat == null) {
		return OrphanResolution.none;
	}
	if (resVals.includes(strat)) {
		return strat;
	}
	return OrphanResolution.assign;
}

const autogenService = {
	description: 'Autogenerated Service',
	baseUrl: 'unknown',
	name: 'Autogenerated Service',
};

const autogenEndpoint = { name: 'Autogenerated Endpoint' };

export function AdoptionOverlay({ orphanData }: AdoptionOverlayProps) {
	const [strategy, setStrategy] = useState<OrphanStrategy>({});
	const services = useSelector(selectServices);
	const endpoints = useSelector(selectEndpoints);
	const serviceList = useMemo(() => Object.values(services), [services]);
	const endpointList = useMemo(() => Object.values(endpoints), [endpoints]);
	const dispatch = useAppDispatch();

	if (orphanData == null) {
		return null;
	}

	const onApply = async () => {
		const {
			delete: deleteEndpoints,
			create: createEndpoints,
			revive: reviveEndpoints,
			assign: assignEndpoints,
		} = groupBy(orphanData.endpoints, (item) => getGroup(strategy[item.orphan.id]));
		const {
			delete: deleteRequests,
			create: createRequests,
			revive: reviveRequests,
			assign: assignRequests,
		} = groupBy(orphanData.requests, (item) => getGroup(strategy[item.orphan.id]));

		const revivedIds = new Set();
		if (reviveEndpoints?.length || reviveRequests?.length) {
			reviveEndpoints?.forEach(({ parent }) => {
				if (parent == null) {
					throw new Error('trying to revive a non-existent parent');
				}
				if (!revivedIds.has(parent)) {
					activeActions.insertService(orphanData.ancestors[parent] as Service);
					revivedIds.add(parent);
				}
			});
			reviveRequests?.forEach(({ parent, grandparent }) => {
				if (parent == null || grandparent == null) {
					throw new Error('trying to revive a non-existent parent or grandparent');
				}
				if (services[grandparent] == null && !revivedIds.has(grandparent)) {
					activeActions.insertService(orphanData.ancestors[grandparent] as Service);
					revivedIds.add(grandparent);
				}
				if (!revivedIds.has(parent)) {
					activeActions.insertEndpoint(orphanData.ancestors[parent] as Endpoint);
				}
			});
		}

		deleteRequests?.forEach(({ orphan }) => dispatch(itemActions.request.delete(orphan.id)));
		deleteEndpoints?.forEach(({ orphan }) => dispatch(itemActions.endpoint.delete(orphan.id)));

		assignEndpoints?.forEach(({ orphan }) =>
			activeActions.addEndpointToService({ id: orphan.id, serviceId: strategy[orphan.id] }),
		);
		assignRequests?.forEach(({ orphan }) =>
			activeActions.addRequestToEndpoint({ id: orphan.id, endpointId: strategy[orphan.id] }),
		);

		if (createEndpoints?.length || createRequests?.length) {
			const serviceId = await dispatch(itemActions.service.create(autogenService)).unwrap();
			createEndpoints?.forEach(({ orphan }) =>
				dispatch(activeActions.addEndpointToService({ id: orphan.id, serviceId })),
			);
			if (createRequests?.length) {
				const endpointId = await dispatch(itemActions.endpoint.create({ ...autogenEndpoint, serviceId })).unwrap();
				createRequests?.forEach(({ orphan }) =>
					dispatch(activeActions.addRequestToEndpoint({ id: orphan.id, endpointId })),
				);
			}
		}

		const ids = [
			...Object.keys(orphanData.ancestors),
			...orphanData.endpoints.flatMap(({ orphan }) => [orphan.id, ...orphan.requestIds]),
			...orphanData.requests.map(({ orphan }) => orphan.id),
		];

		dispatch(activeActions.setSyncItems({ ids, value: false }));

		dispatch(uiActions.setOrphans(null));
	};

	const orphanKinds = [
		{ parentType: 'Service', adoptors: serviceList, label: 'Endpoints', orphans: orphanData.endpoints },
		{ parentType: 'Endpoint and Service', adoptors: endpointList, label: 'Requests', orphans: orphanData.requests },
	];

	return (
		<Sheet sx={{ overflowY: 'auto', px: '20px', width: '600px', maxWidth: '100%' }}>
			<Stack gap={2} height="100%">
				<Typography level="body-md">
					Endpoints without parent Services and/or Requests without parent Endpoints have been detected in this
					workspace.
				</Typography>
				<Alert
					sx={{ textAlign: 'center', px: 2 }}
					endDecorator={<Warning sx={{ fontSize: 36 }} />}
					startDecorator={<Warning sx={{ fontSize: 36 }} />}
					color="warning"
				>
					The workspace cannot be accessed until these items are reassigned, restored, or discarded.
				</Alert>
				{orphanKinds.map(({ label, orphans, ...dropdownArgs }) => {
					if (orphans.length === 0) {
						return null;
					}
					return (
						<Fragment key={label}>
							<Typography mt={2} level="title-md">
								{label}
							</Typography>
							{orphans.map(({ orphan, parent }) => {
								return (
									<OrphanResolutionDropdown
										value={strategy[orphan.id]}
										key={orphan.id}
										name={orphan.name}
										parentName={parent == null ? undefined : orphanData.ancestors[parent].name}
										onChange={(id) => setStrategy({ ...strategy, [orphan.id]: id })}
										{...dropdownArgs}
									/>
								);
							})}
						</Fragment>
					);
				})}
				<Typography mt={2} level="title-md">
					Summary
				</Typography>
				<OrphanResolutionSummary strategy={strategy} />
				<Stack direction="row" gap={1} justifyContent="end" mt={2}>
					<Button
						disabled={Object.keys(strategy).length < orphanData.endpoints.length + orphanData.requests.length}
						color="success"
						sx={{ width: '200px' }}
						startDecorator={<Check />}
						onClick={onApply}
					>
						Apply
					</Button>
				</Stack>
			</Stack>
		</Sheet>
	);
}
