name: "tagged-release"

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install & Build"
        run: |
          yarn
          yarn run build:executable
      - name: "Zip Built Bundle"
        run: |
          tar -czvf linux-bundle.tar.gz ./src-tauri/target/release/bundle
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            linux-bundle.tar.gz
